#!/bin/bash

echo


cd ./pypi/

echo
echo "##### clone repository"
./clone


echo "##### bump pypi version"
./bump


echo "##### build the package"
./build

echo "##### build the distribution"
./dist

echo "##### upload to pypi"
./publish

echo
echo "##### now multiple different operations needs to be completed to prepare, build and publish the updated software for various platforms and app markers:"
echo "##### for MS Windows .msi file will be assembled with: make release-windows"
echo "##### for Apple MacOS need a real MacBook, .dmg file will be assembled: make release-macos"
echo "##### for Apple AppStore need a real MacBook to create & distribute XCode project: make release-ios"
echo "##### for Google PlayMarket a .aab and .apk files will be assembled with: make release-android"
echo


exit 0
